### ISSUE TITLE
Remove direct crypto module dependency to support React Native

### ISSUE THREAD

**Issue by KamesCG** [3box/identity-wallet-js#19]
**Describe the bug**
The `crypto` module breaks React Native.

Would be great to use the shim provided by ethers to add the essential `crypto` methods.

**Comment by KamesCG** [comment]
Something odd is happening, because I have `ethers` already installed too.

When I include `identity-wallet` it breaks the `crypto` require for ethers too. However, without `identity wallet`, the `ethers` modules works as expected.

So, maybe because `identity-wallet` doesn't require the shim it appears to rewrite stuff and break `ethers` too?

**Comment by KamesCG** [comment]
Removing `crypto` to create the sha256 hash will fix the problem. Got `ethers` and `identity-wallet` communicating now in a React Native env.

https://github.com/3box/identity-wallet-js/blob/11d7fdb7590c1e7fd63490ad02e81bebab25c87c/src/utils.js#L13

**Comment by KamesCG** [comment]
I realize now it's a futile effort, because the `HDNode` module use `random-bytes` which I thought `ethers` it was shimming, but it's not.

So probably not worth the effort to remove `crypto` because still need the `random-bytes` in RN.

Maybe WASM modules to replace all the node/crypto stuff is a smart long-term move for a React Native environment?

**Comment by oed** [comment]
Thanks for reporting. You're right, we should probably just use `js-sha256` instead. As for problems with `random-bytes`, I've had success with [rn-nodeify](https://github.com/tradle/rn-nodeify) before.

**Comment by KamesCG** [comment]
Quick heads up that using the `dist` version fixed all the React Native Metro `crypto` bundler problems for me. I don't if you guys want to keep non-dist version (for tree shaking) or not, but maybe we can get a React Native fix inlcuded somehow?


```
import {utils} from 'ethers/dist/ethers';
...
this._baseNode = utils.HDNode.fromSeed(this._seed).derivePath(BASE_PATH);
```

**Comment by oed** [comment]
@KamesCG we are no longer importing the entire `ethers` library for size reasons. Did you try using *rn-nodeify* as I mentioned above?

**Comment by KamesCG** [comment]
Yes. My whole app is nodified/cryptoified. I'm running `ethers` nicely.

It's only this library throwing import errors and I believe it's because the Metro compile is not catching the `crypto` module in 3Box and re-setting to `react-native-crypto`.

**Comment by KamesCG** [comment]
It's an old fix from awhile back => https://github.com/ethers-io/ethers.js/issues/268#issuecomment-433158343

I'm gonna make sure I'm running the latest and see if I still have any issues.. I think my `identity-wallet` version might be behind an update or too.

**Comment by oed** [comment]
> catching the crypto module in 3Box

Wait are you running 3box, or IdentityWallet in RN? The former will likely not work at all.

**Comment by KamesCG** [comment]
IdentityWallet.

I'm aware of all the 3Box React Native issues and I'm not going paid enough to want to deal with that headache :)
