### ISSUE TITLE
Opening 3box space using IdentityWallet and seed succeed only once (the first time)

### ISSUE THREAD

**Issue by Sixtysixter** [3box/identity-wallet-js#26]
**Describe the bug**
Using IdentityWallet with a seed to open a box and then a space doesn't work after a page reloading (also using Empty Cache and Hard Reload choice) .
Actually it works only when a space is open for the first time and fails from the second time on. 
Removing cached consent for the space from the localStorage, it works

**To Reproduce**
1. Open a box using an IdentityWallet with a seed 
     `this.idWallet = new IdentityWallet(this.getConsent.bind(this), {seed}); `
     `const threeIdProvider = this.idWallet.get3idProvider();` 
     `this.box = await Box.openBox(null, threeIdProvider); `
2. Open a space on this box, providing a name
      `spaceName = await this.box.openSpace(spaceName);`
3. Set and get some key/value pair
4. Reload the page (or hard reload it), and re-execute step 1 and 2, using the same seed and the same space name.
5. See the error in console

**Expected behavior**
After a page reload, it should be possible to reopen a box using the IdentityWallet and the same seed and then reopen a spce using the same name.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Brave and firefox
- 3box-js: 1.14.0
- IdentityWallet: 1.0.0

**Additional context**
Opening the space after a page reload there is an exception due to an undefined id from Identities as the provided threeId is not fully initialized

Stack trace:
```
Error: id needed to get a key
    at Keystore.getKey (keystore.js:125)
    at Identities.signId (identities.js:50)
    at Identities.createIdentity (identities.js:43)
```

Attached a simple test page that highlights the exception (caught in seedWallet.js:42).
Execute: 
```
yarn
yarn dev
```

the open the browser to 

> https://localhost:8000/seededWallet.html

and try.

[identityWalletStudy.zip](https://github.com/3box/identity-wallet-js/files/3946525/identityWalletStudy.zip)

**Comment by oed** [comment]
Hey @Sixtysixter, thanks for reporting! What versions of 3box-js and IdentityWallet are you using?

**Comment by Sixtysixter** [comment]
Added information in issue body.
3box-js: 1.14.0
IdentityWallet: 1.0.0

**Comment by oed** [comment]
Thanks, sorry I also meant to ask what the error you're seeing is!

**Comment by Sixtysixter** [comment]
Added some additional info and a simple test code.

**Comment by oed** [comment]
Thank you @Sixtysixter Will have a look at your example!

**Comment by oed** [comment]
I can't get your example to work @Sixtysixter could you try replicating the issue with a simpler setup maybe? The code I usually use to test is this:

```js
const Box = require('3box')
const IdentityWallet = require('identity-wallet')
const prompt = require('async-prompt')

const privateKey = '4ccc180e6d9d20eb9e51f00f34947fe6ba8b2373dbc70373f0a31aad2434776f'

async function consent (req) {
  console.log('\n ------ ')
  console.log('App with origin:', req.origin)
  if (req.spaces.length > 0) {
    console.log('is requesting access to spaces:', req.spaces)
  } else {
    console.log('is requesting access to your 3box')
  }
  const confimed = await prompt.confirm('are you sure? (y/n): ')
  return confimed
}

async function start () {
  const idw = new IdentityWallet(consent, { seed: '0x' + privateKey })
  console.log('idw created')

  const provider = idw.get3idProvider()
  const box = await Box.openBox(null, provider)
  console.log('openBox')
  await box.syncDone
  console.log('syncDone')

  const space = await box.openSpace('test')
  console.log('space opened')
  await space.syncDone
  console.log('space synced')

  await space.public.set('foo', 'bar')
  console.log('get', await space.public.get('foo'))
}

try {
  start()
} catch (e) {
  console.error(e)
}
```

**Comment by Sixtysixter** [comment]
I tried the test and it works fine. But the big difference is that my test is running as a Web App in chrome so the localStorage is available, That means the identityWallet stores in local storage the answer got from getConsens function (identity-wallet.js:60). The localStorage survives the page reload so IdentityWallet.isAuthenticated  always returns true (ie the getConsens authorizes the wallet) so the Space doesn't call ThreeId.authenticate that initializes the _subDIDs (ThreeId.js:193). 
Hope this help.

**Comment by oed** [comment]
Oh I see! Thanks for diving in and figuring out what the issue is @Sixtysixter. Should be an easy fix, putting this on the backlog!

**Comment by oed** [comment]
@Sixtysixter This issue have been resolved and will be part of the next 3box-js release!
