### ISSUE TITLE
Create Implement ThreeIdProvider In typescript for WalletConnect

### ISSUE THREAD

**Issue by oed** [3box/identity-wallet-js#9]

**Comment by michaelsena** [comment]
@oed I saw this in the backlog and it was tagged with IDW v1, which we were hoping to release this upcoming sprint. Do we need this or can it wait?

**Comment by oed** [comment]
It can wait I think. Needed for wallets that want to use walletConnect with 3ID. It's not really something that touches IDW itself though.
